### ISSUE TITLE
Upload data to OpenNeuro

### ISSUE THREAD

**Issue by jcohenadad** [spinal-cord-7t/coil-qc-code#19]
@Kyota-exe please describe this issue and add the URL to the database on OpenNeuro

Related to #15

**Comment by Kyota-exe** [comment]
I have uploaded the data on OpenNeuro: https://openneuro.org/datasets/ds005025

As I have not published it publicly yet, I believe only people who have been given access have access to the data for now. I have added @jcohenadad as an administrator. I have also tried to add @evaalonsoortiz as an administrator via the email eva.alonso-ortiz@polymtl.ca, but I get the following error:
![image](https://github.com/spinal-cord-7t/coil-qc-code/assets/56048818/9c84e82e-ac55-4f26-adb2-89d2e04a8a52)

I would appreciate feedback on the dataset settings and `dataset_description.json` file, which I created based on the one for the [RF shimming 7T project](https://openneuro.org/datasets/ds004906), for example regarding the list of authors, as I do not know everyone who contributed to this project and may be missing some authors.

**Comment by Kyota-exe** [comment]
I was also wondering if anyone knows of an effective way to update the dataset. Ideally, I would like to re-upload the entire dataset every time I make modifications to it, as the dataset is generated from the `bids_conversion.py` file and I want to make sure I don't miss any changes I made, but I believe the OpenNeuro interface only allows you to remove/add individual files. One possible solution may be to delete all the directories for the subjects and re-upload each directory one at a time every time I want to update the dataset. Unfortunately this method may become cumbersome when we add more sites.

**Comment by jcohenadad** [comment]
> but I believe the OpenNeuro interface only allows you to remove/add individual files. One possible solution may be to delete all the directories for the subjects and re-upload each directory one at a time every time I want to update the dataset. Unfortunately this method may become cumbersome when we add more sites.

see https://docs.openneuro.org/git.html

**Comment by Kyota-exe** [comment]
Thanks! I’ve updated the OpenNeuro dataset with the fix for DREAM FOVs.

**Comment by jcohenadad** [comment]
>  I’ve updated the OpenNeuro dataset with the fix for DREAM FOVs.

What upload solution did you end up using?

**Comment by evaalonsoortiz** [comment]
@Kyota-exe Can you try with my gmail? eva.alonso.ortiz@gmail.com

**Comment by Kyota-exe** [comment]
@evaalonsoortiz I believe this worked! Can you confirm that you have access as an administrator?

**Comment by Kyota-exe** [comment]
I just updated the notebook to download data from OpenNeuro instead of Google Drive. For now, the notebook uses the OpenNeuro CLI, and assumes the user already installed and logged into the OpenNeuro CLI. Once the repository becomes public, the user will no longer need to login to OpenNeuro to download the data.

@evaalonsoortiz Could you send me the manual segmentations you did? I will update the `bids_conversion.py` script to include them in the OpenNeuro dataset. We could just upload them on OpenNeuro directly, but since I will continue updating and using the `bids_conversion.py` script to regenerate the dataset when I do the DICOM to NIFTI conversion for more sites, I think it may be better to modify this script so that it automatically adds the manual segmentations to the generated dataset so that I can upload the generated dataset to OpenNeuro directly.

**Comment by jcohenadad** [comment]
> I think it might be better to wait until I have the manual segmentations for all subjects, that way I send them to you just once.

I would wait for the automatic processing to be settled, see e.g. #22 (the manual segmentation are not valid anymore)

**Comment by evaalonsoortiz** [comment]
Human and phantom data are now on openneuro:
https://openneuro.org/datasets/ds005025
https://openneuro.org/datasets/ds005090
