### ISSUE TITLE
Consider quantifying g-factor within a mask, or overlaying an anatomical image

### ISSUE THREAD

**Issue by dpapp86** [spinal-cord-7t/coil-qc-code#63]
Related to #62 and #58 and partially to #56 

G-factor maps are usually shown either for simple phantoms, or for "full" anatomy (a brain, an abdominal slice, etc), which makes theme easy to interpret, see examples in #62 and #58.

By contrast, our maps are taken of an area that is mostly "empty" of signal, and will thus not produce nice-looking g-factor maps with a clear border showing foldovers and areas of high g-factor. 

To improve readiblity, I suggest we either agree on a mask in which the g-factor can be quantified (this could be some extended SC mask, since we do not care that much about g-factor in the ribcage), or an anatomical overlay be provided, so the reader can easily see what is important.

**Comment by jcohenadad** [comment]
> we could use the model that was used to design Spinoza to extract a spinal cord ROI. Could you provide me with the images of that model?

Discussed here: https://github.com/neuropoly/phantom-spinoza/issues/5

**Comment by evaalonsoortiz** [comment]
Update: 

I'm now using a spinal cord mask to compute B1+ and SNR in the phantom along the "fake" spinal cord (see: https://github.com/spinal-cord-7t/coil-qc-code/issues/64#issuecomment-2167074164)

This solution requires labels for the TFL, DREAM, and SNR images so that a spinal cord mask could be defined for each one of those images and so that scans could be co-registered across sites. 

If we want to use the spinal cord mask to quantify the average and maximum g-factor, I would need to be able to visually identify the registration label (as was done for TFL, DREAM and SNR). This is not so easy to identify in a g-factor map (see images below). So, my solution is to define a square ROI in the center of the image and compute the average and max g-factor there (this is commonly done in publications from what I've seen).  

Phantom:
<img width="1071" alt="Screenshot 2024-06-19 at 8 50 20 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/2cf194e0-99f4-40d5-882f-752d804861a0">

In-vivo:
<img width="1073" alt="Screenshot 2024-06-19 at 8 50 38 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/50aed01a-6a1d-4d5c-9d97-5387c0e0a350">

If I can get a thumbs up to approve this solution, I'll close this issue.
